use open_orders;

create table customer(
    ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID),
    CUSTOMER_NAME VARCHAR(250) NOT NULL,
    ZONE VARCHAR(50)
    );

create table orders(
    ID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(ID),
    ORDER_NUMBER INT,
    CUSTOMER_NUMBER INT,
    PART VARCHAR(50),
    CURR_CODE VARCHAR(3),
    OPEN_QTY INT,	
    UNIT_PRICE_USD FLOAT(5,2),
    USD_EUR_FXRATE FLOAT(6,5) NOT NULL,
    FOREIGN KEY (CUSTOMER_NUMBER) REFERENCES CUSTOMER(ID)  ON UPDATE CASCADE ON DELETE RESTRICT
    ); 